app_registro/urls.py
from django.urls import path
from . import views 
app_name = 'app_registro'

urlpatterns = [
    path('', views.index, name='index'),
    path('topicos/', views.topicos, name='topicos'),
    path('topicos/<int:topico_id>/', views.topico, name='topico'),
    path('novo_topico/', views.novo_topico, name='novo_topico'),
    path('nova_entrada/<int:topico_id>/', views.nova_entrada, name='nova_entrada'),
    path('editar_entrada/<int:entrada_id>/', views.editar_entrada, name='editar_entrada'),
]

app_usuarios/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
app_name = 'app_usuarios'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='app_usuarios/login.html'), name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('registro/',views.registro, name='registro'),
]

registro_aprendizado/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app_registro.urls')),
    path('app_usuarios/', include('app_usuarios.urls')),
]

app_registro/models.py
from django.db import models
from django.contrib.auth.models import User

class Topico(models.Model):
    texto = models.CharField(max_length=100)
    data_edicao = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.texto
    

class Entrada(models.Model):
    topico = models.ForeignKey(Topico, on_delete=models.CASCADE)
    texto = models.TextField()
    data_edicao = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.texto[:50]+"..."

app_usuarios/models.py
from django.db import models

# Create your models here.

app_registro/forms.py
from django import forms 
from .models import Topico,Entrada

class TopicoForm(forms.ModelForm):
    class Meta:
        model = Topico
        fields = ['texto']
        labels = {'texto':''}

class EntradaForm(forms.ModelForm):
    class Meta:
        model = Entrada
        fields = ['texto']
        labels = {'texto':''}
        widgets = {'texto': forms.Textarea(attrs={'cols':80})}

app_registro/views.py
from django.shortcuts import render
from .models import Topico,Entrada
from .forms import TopicoForm,EntradaForm
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse
from django.contrib.auth.decorators import login_required


def index(request):
    return render(request, 'app_registro/index.html')

@login_required
def topicos(request):
    topicos = Topico.objects.filter(owner=request.user).order_by('data_edicao')
    context = {'topicos':topicos}
    return render(request, 'app_registro/topicos.html', context)

@login_required
def topico(request, topico_id):
    topico = Topico.objects.get(id=topico_id)
    if topico.owner != request.user:
        raise Http404
    
    entradas = topico.entrada_set.order_by('-data_edicao')
    context = {'topico':topico, 'entradas':entradas}
    return render(request, 'app_registro/topico.html',context)

@login_required
def novo_topico(request):
    if request.method != 'POST':
        form = TopicoForm()
    else:
        form = TopicoForm(request.POST)
        if form.is_valid():
            novo_topico = form.save(commit=False)
            novo_topico.owner = request.user
            novo_topico.save()
            return HttpResponseRedirect(reverse('app_registro:topicos'))
        
    context = {'form':form}
    return render(request, 'app_registro/novo_topico.html',context)

@login_required
def nova_entrada(request, topico_id):
    topico = Topico.objects.get(id=topico_id)
    if topico.owner != request.user:
        raise Http404
    
    if request.method != 'POST':
        form = EntradaForm()
    else:
        form = EntradaForm(data=request.POST)
        if form.is_valid():
            nova_entrada = form.save(commit=False)
            nova_entrada.topico = topico
            nova_entrada.save()
            return HttpResponseRedirect(reverse('app_registro:topico', args=[topico_id]))
    context = {'topico':topico, 'form':form}
    return render(request, 'app_registro/nova_entrada.html', context)

@login_required
def editar_entrada(request, entrada_id):
    entrada = Entrada.objects.get(id=entrada_id)
    topico = entrada.topico
    if topico.owner != request.user:
        raise Http404
    
    if request.method != 'POST':
        form = EntradaForm(instance=entrada)
    else:
        form = EntradaForm(instance=entrada, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('app_registro:topico', args=[topico.id]))
    contexto = {'entrada':entrada, 'topico':topico, 'form':form}
    return render(request, 'app_registro/editar_entrada.html', contexto)

app_usuarios/views.py
from django.shortcuts import render 
from django.contrib.auth import logout
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login,authenticate


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('app_registro:index'))

def registro(request):
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            novo_usuario = form.save()
            usuario_autenticado = authenticate(username=novo_usuario.username, password = request.POST['password1'])
            login(request, usuario_autenticado)
            return HttpResponseRedirect(reverse('app_usuarios:login'))
    
    context = {'form':form} 
    return render(request, 'app_usuarios/registro.html', context)  

app_registro/templates/app_registro/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Registro{% endblock title %}</title>
</head>
<body>
    <h1><a href="{% url 'app_registro:index' %}">Registro aprendizado - <a href="{% url 'app_registro:topicos' %}">ver topicos</a></a></h1>
    <p>
        {% if user.is_authenticated %}
        ola, {{ user.username }}
        <a href="{% url 'app_usuarios:logout' %}">Fazer logout</a>
        {% else %}
        <a href="{% url 'app_usuarios:registro' %}">Fazer o registro</a>
        <a href="{% url 'app_usuarios:login' %}">faca o login</a>
        {% endif %}
    </p>
    {% block content %}
    {% endblock content %}
    
</body>
</html>

app_registro/templates/app_registro/editar_entrada.html
{% extends 'app_registro/base.html' %}


{% block content %}
<p><a href="{% url 'app_registro:topico' topico.id %}">{{ topico }}</a></p>
<form action="{% url 'app_registro:editar_entrada' entrada.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Editar</button>
</form>
{% endblock content %}

app_registro/templates/app_registro/index.html
{% extends 'app_registro/base.html' %}


{% block content %}
<p>O siste de registro de aprendizado vai te ajudar nos seus estudos</p>
{% endblock content %}

app_registro/templates/app_registro/nova_entrada.html
{% extends 'app_registro/base.html' %}


{% block content %}
<p>Topico:{{ topico }}</p>
<form action="{% url 'app_registro:nova_entrada' topico.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Adicionar</button>
</form>
{% endblock content %}

app_registro/templates/app_registro/novo_topico.html
{% extends 'app_registro/base.html' %}


{% block content %}
<p>Adicione um novo topico</p>
<form action="{% url 'app_registro:novo_topico' %}" method="post">
    {% csrf_token %}
     {{ form.as_p }}
     <button type="submit">Adicionar</button>
</form>
{% endblock content %}

app_registro/templates/app_registro/topico.html
{% extends 'app_registro/base.html' %}


{% block content %}
<p>Topico:{{ topico }}</p>
<p>Entrada:</p>
<ul>
    {% for entrada in entradas %}
    <li>
        <p>{{ entrada.data_edicao | date:'M d, Y H:i'}}</p>
        <p>{{ entrada.texto | linebreaks }}</p>
        <p>
            <a href="{% url 'app_registro:editar_entrada' entrada.id %}">Editar entrada</a>
        </p>
    </li>
    {% empty %}
    <li>
        <p>Nenhuma entrada encontrada!</p>
    </li>
    {% endfor %}
</ul>
<a href="{% url 'app_registro:nova_entrada' topico.id %}">Adicionar uma nova entrada</a>
{% endblock content %}

app_registro/templates/app_registro/topicos.html
{% extends 'app_registro/base.html' %}


{% block content %}
<p>Topicos:</p>
<ul>
    {% for topico in topicos %}
    <li>
        <p><a href="{% url 'app_registro:topico' topico.id %}">{{ topico }}</a></p>
    </li>
    {% empty %}
    <li>Nenhum topico encontrado!</li>
    {% endfor %}
</ul>
<a href="{% url 'app_registro:novo_topico' %}">Add novo topico</a>
{% endblock content %}

app_usuarios/templates/app_usuarios/login.html
{% extends 'app_registro/base.html' %}


{% block content %}
{% if form.errors %}
{% endif %}
<form action="{% url 'app_usuarios:login' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Logar</button>
    <input type="hidden" name="next" value="{% url 'app_registro:index' %}"/>
</form>
{% endblock content %}

app_usuarios/templates/app_usuarios/registro.html
{% extends 'app_registro/base.html' %}


{% block content %}
{% if form.errors %}
{% endif %}
<form action="{% url 'app_usuarios:registro' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Registar</button>
    <input type="hidden" name="next" value="{% url 'app_registro:index' %}"/>
</form>
{% endblock content %}